const React = require('react-native')
const {StyleSheet, Dimensions} = React
const constants = {
    actionColor: '#24CE84',
    brandMainColor: '#2D2D2D',
    brandSubColor: '#969696',
    red: '#FF4B4B',
    lightRed: '#FF9393',
    green: '#72CC4B',
    lightGreen: '#9CDB81',
    lightGrey: '#D6D6D6',
    dinNextMedium: 'DINNextRoundedLTPro-Medium',
    dinNextBold: 'DINNextRoundedLTPro-Bold',
    dinNextRegular: 'DINNextRoundedLTPro-Regular',
    merriBold: 'Merriweather-Bold',
    merriRegular: 'Merriweather-Regular',
    merriItalic: 'Merriweather-Italic',
    merriBoldItalic: 'MerriWeather-BoldItalic',
    sspBold: 'SourceSansPro-Bold',
    sspBoldItalic: 'SourceSansPro-BoldItalic',
    sspItalic: 'SourceSansPro-Italic',
    sspRegular: 'SourceSansPro-Regular',
    sspSemibold: 'SourceSansPro-Semibold',
};
var dimensions = Dimensions.get('window');
var vheight = dimensions.height;
var vwidth = dimensions.width;

var styles = StyleSheet.create({
    container: {
        backgroundColor: '#FAFAFA',
        flex: 1,
    },
    textBold: {
      fontFamily: constants.dinNextBold,
    },
    textRed: {
        color: constants.red,
    },
    textGreen: {
        color: constants.green,
    },
    textLightRed: {
        color: constants.lightRed,
    },
    textLightGreen: {
        color: constants.lightGreen,
    },
    textLightGrey: {
        color: '#B9B9B9',
    },
    navigator: {
        top: 0,
        flex: 1,
    },
    listview: {
        flex: 1,
        top:0,
        zIndex:1,
    },
    li: {
        backgroundColor: '#fff',
        borderBottomColor: '#E9E9E9',
        borderColor: 'transparent',
        borderWidth: 1,
        paddingBottom: 9,
        paddingHorizontal: 15,
        flex: 1,
        zIndex:1,
    },
    liWithStat: {
        backgroundColor: '#fff',
        borderRadius: 6,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#E9E9E9',
        paddingBottom: 0,
        paddingHorizontal: 0,
        flex: 1,
        marginTop: 10,
        marginLeft: 10,
        marginRight: 10,
        zIndex:1,
    },
    liContainer: {
        flex: 2,
    },
    liHeader: {
        shadowColor: constants.brandMainColor,
        paddingHorizontal: 5,
        paddingTop: 20,
        paddingBottom: 6,
        borderBottomWidth: 0,
    },
    liHeaderWithStat: {
        shadowColor: constants.brandMainColor,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 15,
        shadowOpacity: 0.05,
        borderBottomColor: '#E9E9E9',
        borderBottomWidth: 1,
        zIndex: 5,
        shadowRadius: 3,
        shadowOffset: {
            height: 2,
            width: 0,
        },
    },
    liText: {
        color: constants.brandMainColor,
        fontSize: 18,
        fontFamily: constants.dinNextRegular,
    },
    liStats: {
        flexDirection: 'row',
        shadowOpacity: 0.15,
        paddingHorizontal: 20,
        paddingTop: 15,
        paddingBottom: 12,
        zIndex: 3,
        shadowRadius: 4,
        shadowOffset: {
            height: 2,
            width: 0,
        },

    },
    liStatsRows: {
        flexDirection: 'row',

    },
    liStatsBar: {
        flexDirection: 'row',
        zIndex: 0,
    },
    liStatsProgress: {
        height: 10,
    },
    liSubTextSpan: {
        paddingTop: 2,
        color: constants.brandSubColor,
        opacity: 1,
        fontFamily: constants.dinNextMedium,
        fontSize: 14,
        marginRight: 0,
        minWidth: 90,
    },
    liGradient: {
        height: 8,
        flex: 1,
        marginLeft: -15,
        marginRight: -15,
    },
    navbar: {
        backgroundColor: '#fff',
        borderBottomColor: '#E0E0E0',
        borderColor: 'transparent',
        borderWidth: 1,
        justifyContent: 'center',
        height: 65,
        flexDirection: 'row',
        shadowColor: constants.brandMainColor,
        zIndex: 10,
    },
    navbarButton: {
        backgroundColor: 'transparent',
        left: 15,
        position: 'absolute',
        top: 18,
        height: 42,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',

    },
    navbarTitle: {
        color: constants.brandMainColor,
        fontSize: 16,
        fontWeight: "500",
        paddingTop: 32,
        fontFamily: constants.dinNextMedium,
    },
    viewContainer: {
        top: 0,
        flex: 1,
        backgroundColor: '#FAFAFA',
    },
    loadingView: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingViewText: {
        marginTop: 15,
        fontFamily: constants.dinNextMedium,
        fontSize: 14,
        color: constants.brandSubColor,
    },
    cardWrapper: {
        flex: 1,
    },
    meta: {
        height: 50,
        alignItems: 'center',
        flex: 0,
        justifyContent: 'center',
        zIndex: 2,
        alignSelf: 'center',
        flexDirection: 'row',
        width: vwidth,
    },
    metaText: {
        fontSize: 14,
        color: constants.brandSubColor,
        fontFamily: constants.dinNextMedium,
        alignSelf: 'center',
        paddingTop: 5,
    },
    metaButton: {
        right: 20,
        position: 'absolute',
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    card: {
        height: vheight - 20 - 45 - 50 - 10, // Statusbar - Navbar - Footer - 8px offset from top
        width: vwidth - 20,
        top: 10,
        backgroundColor: 'white',
        borderRadius: 6,
        flexDirection: 'column',
        alignSelf: 'center',
        borderWidth: 1,
        borderColor: 'transparent',
        zIndex: 1,
        shadowColor: '#000000',
        shadowOpacity: 0.15,
        shadowRadius: 2,
        shadowOffset: {
            height: 1,
            width: 0,
        },
    },
    cardsView: {
        flex: 1,
        alignItems: 'center',
        flexDirection: 'column',
        justifyContent: 'center',
        backgroundColor: 'transparent',
    },
    cardBack: {
        backgroundColor: 'transparent',
        alignSelf: 'stretch',
        borderColor: 'transparent',
        zIndex: 1,
        width: vwidth - 16,
        flex: 1,
    },
    viewDivider: {
        height: 1,
        width: 100,
        backgroundColor: constants.brandMainColor,
        opacity: 0.1,
        top: 0,
        marginBottom: 15,
    },
    yup: {
        backgroundColor: constants.green,
        position: 'absolute',
        bottom: -50,
        height: 50,
        borderRadius: 50,
        width: 200,
        left: (vwidth-200)/2,
        alignItems: 'center',
        paddingTop: 18,
        zIndex: 100,
        shadowOpacity: 0.15,
        shadowRadius: 22,
        shadowOffset: {
            height: 0,
            width: 0,
        },
    },
    yupText: {
        color: 'white',
        fontFamily: constants.dinNextMedium,
        fontSize: 16,
    },
    nope: {
        backgroundColor: constants.red,
        position: 'absolute',
        bottom: -50,
        height: 50,
        width: 200,
        left: (vwidth-200)/2,
        borderRadius: 50,
        alignItems: 'center',
        paddingTop: 18,
        zIndex: 100,
        shadowColor: '#000000',
        shadowOpacity: 0.15,
        shadowRadius: 22,
        shadowOffset: {
            height: 0,
            width: 0,
        },
    },
    nopeText: {
        color: 'white',
        fontFamily: constants.dinNextMedium,
        fontSize: 16,
    },
    noMoreCards: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    noMoreCardsText: {
        fontFamily: constants.dinNextRegular,
        color: constants.brandSubColor,
        width: vwidth - 120,
        marginTop: 15,
        marginBottom: 15,
        textAlign: 'center',
        fontSize: 18,
    },
    noMoreCardsEmoji: {
        fontSize: 72,
        marginBottom: 15,
    },
    buttonContainer: {
        marginTop: 15,
        padding:10, height:50, borderRadius:50, backgroundColor: 'white',
        shadowColor: constants.brandMainColor,
        shadowOpacity: 0.15,

        shadowRadius: 5,
        shadowOffset: {
            height: 4,
            width: 0,
        },
        borderColor: '#E0E0E0',
        borderWidth: 1,
        paddingTop: 16,
        width: vwidth - 120,
    },
    buttonText: {
        fontFamily: constants.dinNextMedium,
        color: constants.brandSubColor,
        fontSize: 18,
        backgroundColor: 'white',
        letterSpacing: 2,
    },
    textDivider: {
        height: 1,
        width: 100,
        backgroundColor: constants.brandMainColor,
        opacity: 0.1,
        marginBottom: 15,
        marginTop: 15,
    },
    backgroundImageContainer:{
        justifyContent: 'center',
        alignItems: 'center',
        height: vheight,
        width: vwidth,
        position: 'absolute',
        top: 0,
        left:0,
    },
    backgroundImage: {
        flex: 0,
        alignSelf: 'center',
    },
    loginTextInput: {
        height: 55,
        fontFamily: constants.dinNextMedium,
        color: constants.brandSubColor,
        fontSize: 16,
        flex: 0,
    },
    loginView: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    loginBox: {
        backgroundColor: '#fff',
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#E9E9E9',
        paddingHorizontal: 20,
        alignSelf: 'stretch',
        marginLeft: 10,
        marginRight: 10,
        shadowColor: constants.brandMainColor,
        shadowOpacity: 0.05,
        shadowRadius: 3,
        shadowOffset: {
            height: 2,
            width: 0,
        },
    },
    textInputSeparator: {
        flex: 0,
        alignSelf: 'stretch',
        height: 1,
        backgroundColor: '#EAEAEA',
    },
    buttonGreenContainer: {
        borderWidth: 0,
        backgroundColor: constants.green,
        paddingVertical: 0,
        height: 40,
        width: 200,
        paddingTop: 13,
        marginTop: 50,
    },
    buttonGreenText: {
        fontFamily: constants.dinNextMedium,
        color: 'white',
        fontSize: 16,
        backgroundColor: constants.green,
        letterSpacing: 1,
    },
});

module.exports = styles;
module.exports.constants = constants;